### ISSUE TITLE
2.5章节勘误

### ISSUE THREAD

**Issue by baihongzeng** [hanxiaomax/Learncpp_CN#2]
http://blog.0xfe.cc/Learncpp_CN/2-5-Introduction-to-local-scope/
在2.5章节中，最后一个标题“在何处定义局部变量”内的内容：“函数体内的局部变量，其定义的位置应该尽可能解决其第一次被使用的位置”应为“函数体内的局部变量，其定义的位置应该尽可能接近其第一次被使用的位置”？

**Comment by hanxiaomax** [comment]
fixed
