### ISSUE TITLE
1.5 std:: cin 存在笔误

### ISSUE THREAD

**Issue by CoolKn** [hanxiaomax/Learncpp_CN#27]
std:: cin
std::cin 是 isstream(应该是iostream) 中预定义的另外一个变量。与用于输出的 std::cout 不同， std::cin(表示字符输入，“character input”) 配合提取运算符(>>)，可以从键盘读取输入。当然，输入的结果必须存放在变量中才可以被使用。

**Comment by ganchuanman** [comment]
fix this issue with PR：https://github.com/hanxiaomax/Learncpp_CN/pull/28
